services:
  video-organizer:
    container_name: video-organizer
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - 1panel-network
    volumes:
      # 视频目录
      - /mnt/data1/media/av:/media/av
      - /mnt/data2/media/movies:/media/movies
      - /mnt/data2/media/sv:/media/sv
      # 日志目录
      - ./logs:/app/logs
    environment:
      - CONCURRENCY=3
      - FOLDER_PATHS=/media/av /media/movies /media/sv
networks:
  1panel-network:
    external: true
